# Generated by Django 2.2.4 on 2019-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'MANAGER'), ('MEMBER', 'MEMBER')], default='MEMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('NEEDS_APPROVAL', 'NEEDS_APPROVAL'), ('ACTIVE', 'ACTIVE'), ('OUT', 'OUT')], default='ACTIVE', max_length=20),
        ),
    ]
